version: '3'

services:
  fall-surveillance-mobile:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
